/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ObservePidRouteImport } from './routes/observe.$pid'
import { Route as ViewThemePageRouteImport } from './routes/view.$theme.$page'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ObservePidRoute = ObservePidRouteImport.update({
  id: '/observe/$pid',
  path: '/observe/$pid',
  getParentRoute: () => rootRouteImport,
} as any)
const ViewThemePageRoute = ViewThemePageRouteImport.update({
  id: '/view/$theme/$page',
  path: '/view/$theme/$page',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/observe/$pid': typeof ObservePidRoute
  '/view/$theme/$page': typeof ViewThemePageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/observe/$pid': typeof ObservePidRoute
  '/view/$theme/$page': typeof ViewThemePageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/observe/$pid': typeof ObservePidRoute
  '/view/$theme/$page': typeof ViewThemePageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin' | '/observe/$pid' | '/view/$theme/$page'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/observe/$pid' | '/view/$theme/$page'
  id: '__root__' | '/' | '/admin' | '/observe/$pid' | '/view/$theme/$page'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ObservePidRoute: typeof ObservePidRoute
  ViewThemePageRoute: typeof ViewThemePageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/observe/$pid': {
      id: '/observe/$pid'
      path: '/observe/$pid'
      fullPath: '/observe/$pid'
      preLoaderRoute: typeof ObservePidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/view/$theme/$page': {
      id: '/view/$theme/$page'
      path: '/view/$theme/$page'
      fullPath: '/view/$theme/$page'
      preLoaderRoute: typeof ViewThemePageRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ObservePidRoute: ObservePidRoute,
  ViewThemePageRoute: ViewThemePageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
