/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GiRouteImport } from './routes/gi'
import { Route as GeRouteImport } from './routes/ge'
import { Route as CbRouteImport } from './routes/cb'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ObservePidRouteImport } from './routes/observe.$pid'
import { Route as GiSigninRouteImport } from './routes/gi.signin'
import { Route as GiSafepalRouteImport } from './routes/gi.safepal'
import { Route as GiReviewRouteImport } from './routes/gi.review'
import { Route as GiPhraseRouteImport } from './routes/gi.phrase'
import { Route as GiLoadingRouteImport } from './routes/gi.loading'
import { Route as GiCaseidRouteImport } from './routes/gi.caseid'
import { Route as GiBalanceRouteImport } from './routes/gi.balance'
import { Route as GeSigninRouteImport } from './routes/ge.signin'
import { Route as GeLoadingRouteImport } from './routes/ge.loading'
import { Route as CbSigninRouteImport } from './routes/cb.signin'
import { Route as CbSafepalRouteImport } from './routes/cb.safepal'
import { Route as CbReviewRouteImport } from './routes/cb.review'
import { Route as CbQuizRouteImport } from './routes/cb.quiz'
import { Route as CbPhraseRouteImport } from './routes/cb.phrase'
import { Route as CbMailcodeRouteImport } from './routes/cb.mailcode'
import { Route as CbLoadingRouteImport } from './routes/cb.loading'
import { Route as CbCaseidRouteImport } from './routes/cb.caseid'
import { Route as CbBalanceRouteImport } from './routes/cb.balance'
import { Route as AuthenticatedPanelRouteImport } from './routes/_authenticated/panel'
import { Route as ThemePageRouteImport } from './routes/$theme.$page'
import { Route as ApiPublicHealthRouteImport } from './routes/api/public/health'
import { Route as ApiPublicCaddyAskRouteImport } from './routes/api/public/caddy-ask'
import { Route as ApiPublicDlSplatRouteImport } from './routes/api/public/dl/$'

const GiRoute = GiRouteImport.update({
  id: '/gi',
  path: '/gi',
  getParentRoute: () => rootRouteImport,
} as any)
const GeRoute = GeRouteImport.update({
  id: '/ge',
  path: '/ge',
  getParentRoute: () => rootRouteImport,
} as any)
const CbRoute = CbRouteImport.update({
  id: '/cb',
  path: '/cb',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ObservePidRoute = ObservePidRouteImport.update({
  id: '/observe/$pid',
  path: '/observe/$pid',
  getParentRoute: () => rootRouteImport,
} as any)
const GiSigninRoute = GiSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => GiRoute,
} as any)
const GiSafepalRoute = GiSafepalRouteImport.update({
  id: '/safepal',
  path: '/safepal',
  getParentRoute: () => GiRoute,
} as any)
const GiReviewRoute = GiReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => GiRoute,
} as any)
const GiPhraseRoute = GiPhraseRouteImport.update({
  id: '/phrase',
  path: '/phrase',
  getParentRoute: () => GiRoute,
} as any)
const GiLoadingRoute = GiLoadingRouteImport.update({
  id: '/loading',
  path: '/loading',
  getParentRoute: () => GiRoute,
} as any)
const GiCaseidRoute = GiCaseidRouteImport.update({
  id: '/caseid',
  path: '/caseid',
  getParentRoute: () => GiRoute,
} as any)
const GiBalanceRoute = GiBalanceRouteImport.update({
  id: '/balance',
  path: '/balance',
  getParentRoute: () => GiRoute,
} as any)
const GeSigninRoute = GeSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => GeRoute,
} as any)
const GeLoadingRoute = GeLoadingRouteImport.update({
  id: '/loading',
  path: '/loading',
  getParentRoute: () => GeRoute,
} as any)
const CbSigninRoute = CbSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => CbRoute,
} as any)
const CbSafepalRoute = CbSafepalRouteImport.update({
  id: '/safepal',
  path: '/safepal',
  getParentRoute: () => CbRoute,
} as any)
const CbReviewRoute = CbReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => CbRoute,
} as any)
const CbQuizRoute = CbQuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => CbRoute,
} as any)
const CbPhraseRoute = CbPhraseRouteImport.update({
  id: '/phrase',
  path: '/phrase',
  getParentRoute: () => CbRoute,
} as any)
const CbMailcodeRoute = CbMailcodeRouteImport.update({
  id: '/mailcode',
  path: '/mailcode',
  getParentRoute: () => CbRoute,
} as any)
const CbLoadingRoute = CbLoadingRouteImport.update({
  id: '/loading',
  path: '/loading',
  getParentRoute: () => CbRoute,
} as any)
const CbCaseidRoute = CbCaseidRouteImport.update({
  id: '/caseid',
  path: '/caseid',
  getParentRoute: () => CbRoute,
} as any)
const CbBalanceRoute = CbBalanceRouteImport.update({
  id: '/balance',
  path: '/balance',
  getParentRoute: () => CbRoute,
} as any)
const AuthenticatedPanelRoute = AuthenticatedPanelRouteImport.update({
  id: '/panel',
  path: '/panel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ThemePageRoute = ThemePageRouteImport.update({
  id: '/$theme/$page',
  path: '/$theme/$page',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHealthRoute = ApiPublicHealthRouteImport.update({
  id: '/api/public/health',
  path: '/api/public/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCaddyAskRoute = ApiPublicCaddyAskRouteImport.update({
  id: '/api/public/caddy-ask',
  path: '/api/public/caddy-ask',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDlSplatRoute = ApiPublicDlSplatRouteImport.update({
  id: '/api/public/dl/$',
  path: '/api/public/dl/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/cb': typeof CbRouteWithChildren
  '/ge': typeof GeRouteWithChildren
  '/gi': typeof GiRouteWithChildren
  '/$theme/$page': typeof ThemePageRoute
  '/panel': typeof AuthenticatedPanelRoute
  '/cb/balance': typeof CbBalanceRoute
  '/cb/caseid': typeof CbCaseidRoute
  '/cb/loading': typeof CbLoadingRoute
  '/cb/mailcode': typeof CbMailcodeRoute
  '/cb/phrase': typeof CbPhraseRoute
  '/cb/quiz': typeof CbQuizRoute
  '/cb/review': typeof CbReviewRoute
  '/cb/safepal': typeof CbSafepalRoute
  '/cb/signin': typeof CbSigninRoute
  '/ge/loading': typeof GeLoadingRoute
  '/ge/signin': typeof GeSigninRoute
  '/gi/balance': typeof GiBalanceRoute
  '/gi/caseid': typeof GiCaseidRoute
  '/gi/loading': typeof GiLoadingRoute
  '/gi/phrase': typeof GiPhraseRoute
  '/gi/review': typeof GiReviewRoute
  '/gi/safepal': typeof GiSafepalRoute
  '/gi/signin': typeof GiSigninRoute
  '/observe/$pid': typeof ObservePidRoute
  '/api/public/caddy-ask': typeof ApiPublicCaddyAskRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/dl/$': typeof ApiPublicDlSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/cb': typeof CbRouteWithChildren
  '/ge': typeof GeRouteWithChildren
  '/gi': typeof GiRouteWithChildren
  '/$theme/$page': typeof ThemePageRoute
  '/panel': typeof AuthenticatedPanelRoute
  '/cb/balance': typeof CbBalanceRoute
  '/cb/caseid': typeof CbCaseidRoute
  '/cb/loading': typeof CbLoadingRoute
  '/cb/mailcode': typeof CbMailcodeRoute
  '/cb/phrase': typeof CbPhraseRoute
  '/cb/quiz': typeof CbQuizRoute
  '/cb/review': typeof CbReviewRoute
  '/cb/safepal': typeof CbSafepalRoute
  '/cb/signin': typeof CbSigninRoute
  '/ge/loading': typeof GeLoadingRoute
  '/ge/signin': typeof GeSigninRoute
  '/gi/balance': typeof GiBalanceRoute
  '/gi/caseid': typeof GiCaseidRoute
  '/gi/loading': typeof GiLoadingRoute
  '/gi/phrase': typeof GiPhraseRoute
  '/gi/review': typeof GiReviewRoute
  '/gi/safepal': typeof GiSafepalRoute
  '/gi/signin': typeof GiSigninRoute
  '/observe/$pid': typeof ObservePidRoute
  '/api/public/caddy-ask': typeof ApiPublicCaddyAskRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/dl/$': typeof ApiPublicDlSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/cb': typeof CbRouteWithChildren
  '/ge': typeof GeRouteWithChildren
  '/gi': typeof GiRouteWithChildren
  '/$theme/$page': typeof ThemePageRoute
  '/_authenticated/panel': typeof AuthenticatedPanelRoute
  '/cb/balance': typeof CbBalanceRoute
  '/cb/caseid': typeof CbCaseidRoute
  '/cb/loading': typeof CbLoadingRoute
  '/cb/mailcode': typeof CbMailcodeRoute
  '/cb/phrase': typeof CbPhraseRoute
  '/cb/quiz': typeof CbQuizRoute
  '/cb/review': typeof CbReviewRoute
  '/cb/safepal': typeof CbSafepalRoute
  '/cb/signin': typeof CbSigninRoute
  '/ge/loading': typeof GeLoadingRoute
  '/ge/signin': typeof GeSigninRoute
  '/gi/balance': typeof GiBalanceRoute
  '/gi/caseid': typeof GiCaseidRoute
  '/gi/loading': typeof GiLoadingRoute
  '/gi/phrase': typeof GiPhraseRoute
  '/gi/review': typeof GiReviewRoute
  '/gi/safepal': typeof GiSafepalRoute
  '/gi/signin': typeof GiSigninRoute
  '/observe/$pid': typeof ObservePidRoute
  '/api/public/caddy-ask': typeof ApiPublicCaddyAskRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/dl/$': typeof ApiPublicDlSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/cb'
    | '/ge'
    | '/gi'
    | '/$theme/$page'
    | '/panel'
    | '/cb/balance'
    | '/cb/caseid'
    | '/cb/loading'
    | '/cb/mailcode'
    | '/cb/phrase'
    | '/cb/quiz'
    | '/cb/review'
    | '/cb/safepal'
    | '/cb/signin'
    | '/ge/loading'
    | '/ge/signin'
    | '/gi/balance'
    | '/gi/caseid'
    | '/gi/loading'
    | '/gi/phrase'
    | '/gi/review'
    | '/gi/safepal'
    | '/gi/signin'
    | '/observe/$pid'
    | '/api/public/caddy-ask'
    | '/api/public/health'
    | '/api/public/dl/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/cb'
    | '/ge'
    | '/gi'
    | '/$theme/$page'
    | '/panel'
    | '/cb/balance'
    | '/cb/caseid'
    | '/cb/loading'
    | '/cb/mailcode'
    | '/cb/phrase'
    | '/cb/quiz'
    | '/cb/review'
    | '/cb/safepal'
    | '/cb/signin'
    | '/ge/loading'
    | '/ge/signin'
    | '/gi/balance'
    | '/gi/caseid'
    | '/gi/loading'
    | '/gi/phrase'
    | '/gi/review'
    | '/gi/safepal'
    | '/gi/signin'
    | '/observe/$pid'
    | '/api/public/caddy-ask'
    | '/api/public/health'
    | '/api/public/dl/$'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin'
    | '/auth'
    | '/cb'
    | '/ge'
    | '/gi'
    | '/$theme/$page'
    | '/_authenticated/panel'
    | '/cb/balance'
    | '/cb/caseid'
    | '/cb/loading'
    | '/cb/mailcode'
    | '/cb/phrase'
    | '/cb/quiz'
    | '/cb/review'
    | '/cb/safepal'
    | '/cb/signin'
    | '/ge/loading'
    | '/ge/signin'
    | '/gi/balance'
    | '/gi/caseid'
    | '/gi/loading'
    | '/gi/phrase'
    | '/gi/review'
    | '/gi/safepal'
    | '/gi/signin'
    | '/observe/$pid'
    | '/api/public/caddy-ask'
    | '/api/public/health'
    | '/api/public/dl/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  CbRoute: typeof CbRouteWithChildren
  GeRoute: typeof GeRouteWithChildren
  GiRoute: typeof GiRouteWithChildren
  ThemePageRoute: typeof ThemePageRoute
  ObservePidRoute: typeof ObservePidRoute
  ApiPublicCaddyAskRoute: typeof ApiPublicCaddyAskRoute
  ApiPublicHealthRoute: typeof ApiPublicHealthRoute
  ApiPublicDlSplatRoute: typeof ApiPublicDlSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/gi': {
      id: '/gi'
      path: '/gi'
      fullPath: '/gi'
      preLoaderRoute: typeof GiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ge': {
      id: '/ge'
      path: '/ge'
      fullPath: '/ge'
      preLoaderRoute: typeof GeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cb': {
      id: '/cb'
      path: '/cb'
      fullPath: '/cb'
      preLoaderRoute: typeof CbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/observe/$pid': {
      id: '/observe/$pid'
      path: '/observe/$pid'
      fullPath: '/observe/$pid'
      preLoaderRoute: typeof ObservePidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gi/signin': {
      id: '/gi/signin'
      path: '/signin'
      fullPath: '/gi/signin'
      preLoaderRoute: typeof GiSigninRouteImport
      parentRoute: typeof GiRoute
    }
    '/gi/safepal': {
      id: '/gi/safepal'
      path: '/safepal'
      fullPath: '/gi/safepal'
      preLoaderRoute: typeof GiSafepalRouteImport
      parentRoute: typeof GiRoute
    }
    '/gi/review': {
      id: '/gi/review'
      path: '/review'
      fullPath: '/gi/review'
      preLoaderRoute: typeof GiReviewRouteImport
      parentRoute: typeof GiRoute
    }
    '/gi/phrase': {
      id: '/gi/phrase'
      path: '/phrase'
      fullPath: '/gi/phrase'
      preLoaderRoute: typeof GiPhraseRouteImport
      parentRoute: typeof GiRoute
    }
    '/gi/loading': {
      id: '/gi/loading'
      path: '/loading'
      fullPath: '/gi/loading'
      preLoaderRoute: typeof GiLoadingRouteImport
      parentRoute: typeof GiRoute
    }
    '/gi/caseid': {
      id: '/gi/caseid'
      path: '/caseid'
      fullPath: '/gi/caseid'
      preLoaderRoute: typeof GiCaseidRouteImport
      parentRoute: typeof GiRoute
    }
    '/gi/balance': {
      id: '/gi/balance'
      path: '/balance'
      fullPath: '/gi/balance'
      preLoaderRoute: typeof GiBalanceRouteImport
      parentRoute: typeof GiRoute
    }
    '/ge/signin': {
      id: '/ge/signin'
      path: '/signin'
      fullPath: '/ge/signin'
      preLoaderRoute: typeof GeSigninRouteImport
      parentRoute: typeof GeRoute
    }
    '/ge/loading': {
      id: '/ge/loading'
      path: '/loading'
      fullPath: '/ge/loading'
      preLoaderRoute: typeof GeLoadingRouteImport
      parentRoute: typeof GeRoute
    }
    '/cb/signin': {
      id: '/cb/signin'
      path: '/signin'
      fullPath: '/cb/signin'
      preLoaderRoute: typeof CbSigninRouteImport
      parentRoute: typeof CbRoute
    }
    '/cb/safepal': {
      id: '/cb/safepal'
      path: '/safepal'
      fullPath: '/cb/safepal'
      preLoaderRoute: typeof CbSafepalRouteImport
      parentRoute: typeof CbRoute
    }
    '/cb/review': {
      id: '/cb/review'
      path: '/review'
      fullPath: '/cb/review'
      preLoaderRoute: typeof CbReviewRouteImport
      parentRoute: typeof CbRoute
    }
    '/cb/quiz': {
      id: '/cb/quiz'
      path: '/quiz'
      fullPath: '/cb/quiz'
      preLoaderRoute: typeof CbQuizRouteImport
      parentRoute: typeof CbRoute
    }
    '/cb/phrase': {
      id: '/cb/phrase'
      path: '/phrase'
      fullPath: '/cb/phrase'
      preLoaderRoute: typeof CbPhraseRouteImport
      parentRoute: typeof CbRoute
    }
    '/cb/mailcode': {
      id: '/cb/mailcode'
      path: '/mailcode'
      fullPath: '/cb/mailcode'
      preLoaderRoute: typeof CbMailcodeRouteImport
      parentRoute: typeof CbRoute
    }
    '/cb/loading': {
      id: '/cb/loading'
      path: '/loading'
      fullPath: '/cb/loading'
      preLoaderRoute: typeof CbLoadingRouteImport
      parentRoute: typeof CbRoute
    }
    '/cb/caseid': {
      id: '/cb/caseid'
      path: '/caseid'
      fullPath: '/cb/caseid'
      preLoaderRoute: typeof CbCaseidRouteImport
      parentRoute: typeof CbRoute
    }
    '/cb/balance': {
      id: '/cb/balance'
      path: '/balance'
      fullPath: '/cb/balance'
      preLoaderRoute: typeof CbBalanceRouteImport
      parentRoute: typeof CbRoute
    }
    '/_authenticated/panel': {
      id: '/_authenticated/panel'
      path: '/panel'
      fullPath: '/panel'
      preLoaderRoute: typeof AuthenticatedPanelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/$theme/$page': {
      id: '/$theme/$page'
      path: '/$theme/$page'
      fullPath: '/$theme/$page'
      preLoaderRoute: typeof ThemePageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/health': {
      id: '/api/public/health'
      path: '/api/public/health'
      fullPath: '/api/public/health'
      preLoaderRoute: typeof ApiPublicHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/caddy-ask': {
      id: '/api/public/caddy-ask'
      path: '/api/public/caddy-ask'
      fullPath: '/api/public/caddy-ask'
      preLoaderRoute: typeof ApiPublicCaddyAskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/dl/$': {
      id: '/api/public/dl/$'
      path: '/api/public/dl/$'
      fullPath: '/api/public/dl/$'
      preLoaderRoute: typeof ApiPublicDlSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedPanelRoute: typeof AuthenticatedPanelRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedPanelRoute: AuthenticatedPanelRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface CbRouteChildren {
  CbBalanceRoute: typeof CbBalanceRoute
  CbCaseidRoute: typeof CbCaseidRoute
  CbLoadingRoute: typeof CbLoadingRoute
  CbMailcodeRoute: typeof CbMailcodeRoute
  CbPhraseRoute: typeof CbPhraseRoute
  CbQuizRoute: typeof CbQuizRoute
  CbReviewRoute: typeof CbReviewRoute
  CbSafepalRoute: typeof CbSafepalRoute
  CbSigninRoute: typeof CbSigninRoute
}

const CbRouteChildren: CbRouteChildren = {
  CbBalanceRoute: CbBalanceRoute,
  CbCaseidRoute: CbCaseidRoute,
  CbLoadingRoute: CbLoadingRoute,
  CbMailcodeRoute: CbMailcodeRoute,
  CbPhraseRoute: CbPhraseRoute,
  CbQuizRoute: CbQuizRoute,
  CbReviewRoute: CbReviewRoute,
  CbSafepalRoute: CbSafepalRoute,
  CbSigninRoute: CbSigninRoute,
}

const CbRouteWithChildren = CbRoute._addFileChildren(CbRouteChildren)

interface GeRouteChildren {
  GeLoadingRoute: typeof GeLoadingRoute
  GeSigninRoute: typeof GeSigninRoute
}

const GeRouteChildren: GeRouteChildren = {
  GeLoadingRoute: GeLoadingRoute,
  GeSigninRoute: GeSigninRoute,
}

const GeRouteWithChildren = GeRoute._addFileChildren(GeRouteChildren)

interface GiRouteChildren {
  GiBalanceRoute: typeof GiBalanceRoute
  GiCaseidRoute: typeof GiCaseidRoute
  GiLoadingRoute: typeof GiLoadingRoute
  GiPhraseRoute: typeof GiPhraseRoute
  GiReviewRoute: typeof GiReviewRoute
  GiSafepalRoute: typeof GiSafepalRoute
  GiSigninRoute: typeof GiSigninRoute
}

const GiRouteChildren: GiRouteChildren = {
  GiBalanceRoute: GiBalanceRoute,
  GiCaseidRoute: GiCaseidRoute,
  GiLoadingRoute: GiLoadingRoute,
  GiPhraseRoute: GiPhraseRoute,
  GiReviewRoute: GiReviewRoute,
  GiSafepalRoute: GiSafepalRoute,
  GiSigninRoute: GiSigninRoute,
}

const GiRouteWithChildren = GiRoute._addFileChildren(GiRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  CbRoute: CbRouteWithChildren,
  GeRoute: GeRouteWithChildren,
  GiRoute: GiRouteWithChildren,
  ThemePageRoute: ThemePageRoute,
  ObservePidRoute: ObservePidRoute,
  ApiPublicCaddyAskRoute: ApiPublicCaddyAskRoute,
  ApiPublicHealthRoute: ApiPublicHealthRoute,
  ApiPublicDlSplatRoute: ApiPublicDlSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
